# Generated by Django 5.2.13 on 2026-04-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0010_remove_palco_acessibilidade_mobilidade_reduzida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concerto',
            options={},
        ),
    ]
