# Generated by Django 5.2.13 on 2026-04-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0011_alter_concerto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concerto',
            options={'ordering': ['dia__data', 'hora']},
        ),
        migrations.AddField(
            model_name='palco',
            name='acessibilidade_mobilidade_reduzida',
            field=models.BooleanField(default=False),
        ),
    ]
